# Generated by Django 5.0.6 on 2024-07-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('valor_factor', models.IntegerField()),
                ('link_pago', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Planes',
                'verbose_name_plural': 'Planess',
            },
        ),
    ]
