# Generated by Django 4.2.13 on 2024-07-03 05:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id_memorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Memorial',
                'verbose_name_plural': 'Memorials',
            },
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('valor_factor', models.IntegerField()),
                ('link_pago', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Planes',
                'verbose_name_plural': 'Planess',
            },
        ),
        migrations.CreateModel(
            name='Recuerdos',
            fields=[
                ('id_recuerdo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_recuerdo', models.CharField(default='Nombre Recuerdo', max_length=100)),
                ('descripcion_recuerdo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios_Planes',
            fields=[
                ('id_plan_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField(default=0)),
                ('fecha_act', models.DateField(default=datetime.date.today)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoria.planes')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=128)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoria.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_familiar', models.CharField(max_length=100)),
                ('apellidos_familiar', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_deceso', models.DateField()),
                ('parentezco', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(choices=[('AR', 'Argentina'), ('BO', 'Bolivia'), ('BR', 'Brasil'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('EC', 'Ecuador'), ('SV', 'El Salvador'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('MX', 'México'), ('NI', 'Nicaragua'), ('PA', 'Panamá'), ('PY', 'Paraguay'), ('PE', 'Perú'), ('PR', 'Puerto Rico'), ('DO', 'República Dominicana'), ('UY', 'Uruguay'), ('VE', 'Venezuela'), ('OT', 'Otra')], default='CL', max_length=2)),
                ('avatar_picture', models.ImageField(blank=True, null=True, upload_to='familiares_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
