# Generated by Django 4.2.1 on 2024-07-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='hash',
        ),
    ]
