# Generated by Django 5.0.6 on 2024-07-09 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planes',
            options={'verbose_name': 'Planes', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AddField(
            model_name='familiares',
            name='unique_hash',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='familiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images_set', to='memoria.familiares'),
        ),
    ]
