# Generated by Django 5.0.6 on 2024-07-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0002_alter_planes_options_familiares_unique_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='familiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='memoria.familiares'),
        ),
    ]
