# Generated by Django 4.2.1 on 2024-07-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0003_alter_additionalimage_familiar'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
